name: ci
on:  
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: env
      run: |
        set -x
        pwd
        ls -al || true
        ls -al 3m-common || true
        ls -al 3m-common/scripts || true
        find . -ls 
        TARGET_VERSION="${GITHUB_REF:10}" TARGET_BUILD="${{ github.run_number }}" TARGET_REGISTRY_TOKEN="${{ secrets.TARGET_REGISTRY_TOKEN }}" ARGET_REGISTRY_USER="${{ github.actor }}" GITHUB_ENV="${GITHUB_ENV}" ./3m-common/scripts/env.sh 
    - name: preaction
      run: ./3m-common/scripts/preaction.sh
    - name: runaction
      run: ./3m-common/scripts/runaction.sh
    - name: postaction
      run: ./3m-commona/scripts/postaction.sh

